# Server configuration
server.port=8081
server.servlet.context-path=/

# Gatling configuration
gatling.jars.dir=/Users/vitvasilyuk/IdeaProjects/gatling-web-console/simulations
gatling.tests.dir=./gatling-tests
gatling.results.dir=./gatling-results

# Multipart file upload configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Logging configuration
logging.level.org.testing.pt=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Security configuration
api.security.username=admin
api.security.password=password

debug=false